### ISSUE TITLE
Inventory wouldnt open

### ISSUE THREAD

**Issue by JeyCraft** [Randolio/randol_newspaper#5]
When i start the job i cant open the Inventory. Just hotbar works.

https://github.com/Randolio/randol_newspaper/assets/63811758/b787980a-b31d-498b-9ce7-8cd37365a6ed

**Comment by Randolio** [comment]
> When i start the job i cant open the Inventory. Just hotbar works.
> 
>  2024-04-10.15-41-13.mp4

That’s not a bug. That’s an ox inventory feature for bicycles because they don’t have gloveboxes so it prevents you from opening the inventory.
